name: tf-apply

on:
  workflow_dispatch:
  
env:
  BUCKET: ebs-vikramkishore
  TFSTATE_FILE: vikramebs.tfstate
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash


    steps:

    - name: checkout
      uses: actions/checkout@v1
        
    # install the latest version of terraform CLI and configure the terraform CLI configure file with terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-south-1

    - name: Terraform Init
      run : |
        cd Example 
        terraform init -reconfigure -backend-config="bucket=$BUCKET" -backend-config="key=$TFSTATE_FILE"
    - name: Terraform validate
      run: |
        cd Example
        terraform validate -no-color
    - name: Terraform Plan
      run: |
        cd Example
        terraform plan -no-color
    #Generate an execution apply for terraform   
    - name: Terraform Apply
       #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |B4-B0-24-6D-E6-A7
                            {(ASIAZ3CUIHQKMSJTADLR)}
        cd Example
        terraform apply -auto-approve
